import {useMemo,useState} from 'react';
import Layout from '@theme/Layout';import Heading from '@theme/Heading';import Link from '@docusaurus/Link';import {useLocation} from '@docusaurus/router';
import CometGuide from '../../components/CometGuide';import styles from './creativePaths.module.css';
import DraftControls from '../../components/DraftControls';import {upsertNotebookEntry} from '../../lib/notebookStorage';import {useBrowserDraft} from '../../lib/useBrowserDraft';
const API='https://chloelabs-learn-api.chloelabs-amanda.workers.dev',formats=['short talk','poster','demo','quiz','mini lesson','help me choose'],times=['30 minutes','a few hours','several days'];
export default function SharePath(){const location=useLocation(),topic=useMemo(()=>new URLSearchParams(location.search).get('topic')?.trim()||'something interesting',[location.search]);
 const resumeId=useMemo(()=>new URLSearchParams(location.search).get('resume')||'',[location.search]);
 const [format,setFormat]=useState('help me choose'),[time,setTime]=useState('30 minutes'),[audience,setAudience]=useState('family'),[ideas,setIdeas]=useState([]),[idea,setIdea]=useState(null),[hook,setHook]=useState(''),[points,setPoints]=useState([]),[activity,setActivity]=useState(''),[closing,setClosing]=useState(''),[rehearsed,setRehearsed]=useState(false),[status,setStatus]=useState('idle'),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 const draftSnapshot=useMemo(()=>({format,time,audience,ideas,idea,hook,points,activity,closing,rehearsed,saved}),[format,time,audience,ideas,idea,hook,points,activity,closing,rehearsed,saved]);
 const draft=useBrowserDraft({path:'share',topic,resumeId,snapshot:draftSnapshot,resumeToDraft:(entry)=>({format:entry.idea?.format||'help me choose',time:'30 minutes',audience:entry.audience||'family',ideas:entry.idea?[entry.idea]:[],idea:entry.idea||null,hook:entry.hook||'',points:entry.points||[],activity:entry.activity||'',closing:entry.closing||'',rehearsed:true,saved:true}),restore:(data)=>{setFormat(data.format||'help me choose');setTime(data.time||'30 minutes');setAudience(data.audience||'family');setIdeas(Array.isArray(data.ideas)?data.ideas:[]);setIdea(data.idea||null);setHook(data.hook||'');setPoints(Array.isArray(data.points)?data.points:[]);setActivity(data.activity||'');setClosing(data.closing||'');setRehearsed(Boolean(data.rehearsed));setSaved(Boolean(data.saved))}});
 async function generate(){setStatus('loading');setError('');try{const r=await fetch(`${API}/api/share/ideas`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,ageBand:'10-12',format,time,audience})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not prepare the stage.');setIdeas(d.ideas);setStatus('ready')}catch(e){setError(e.message);setStatus('error')}}
 function choose(x){setIdea(x);setHook('');setPoints(x.keyPoints.map(()=>''));setActivity('');setClosing('');setRehearsed(false);setSaved(false)}
 const filled=[hook,...points,activity,closing].filter(x=>x.trim()).length,total=idea?idea.keyPoints.length+3:1;
 function save(){if(!idea||!rehearsed||filled<total)return;upsertNotebookEntry('chloelabs:share-notebook:v1',{id:draft.projectId,topic,audience,idea,hook,points,activity,closing,savedAt:new Date().toISOString()});setSaved(true)}
 function startOver(){if(!window.confirm('Start this sharing plan over? Your notebook entry will stay saved.'))return;draft.clearDraft();setFormat('help me choose');setTime('30 minutes');setAudience('family');setIdeas([]);setIdea(null);setHook('');setPoints([]);setActivity('');setClosing('');setRehearsed(false);setStatus('idle');setError('');setSaved(false)}
 const message=saved?'Curtain call! Your explanation is rehearsed and saved.':idea?filled<total?`${filled} of ${total} stage lights are on. Explain each part in your own words.`:rehearsed?'You rehearsed it! Your audience now has a clear path through the idea.':'All the lights are on. Try saying it aloud before you save.':ideas.length?'Choose the plan that best fits your audience—not the fanciest one.':'Who are you helping understand this? Great sharing begins with the audience.';
 return <Layout title={`Share what you know about ${topic}`}><main className={`${styles.page} ${styles.sharePage}`}><header className={styles.hero}><div className="container"><Link className={styles.back} to={`/curiosity-engine?topic=${encodeURIComponent(topic)}`}>← Choose another path</Link><span>Share path</span><Heading as="h1">Share {topic}</Heading><p>Turn what you know into something another person can understand.</p></div></header><div className={`container ${styles.content}`}><DraftControls noun="sharing plan" onStartOver={startOver} restored={draft.restored} status={draft.status}/><CometGuide role="stage" mood={saved?'celebrate':'thinking'} badge={saved?'Curtain call':'Story stage'} message={message}/>
 <Panel n="1" title="Know your audience"><label className={styles.label}>Who will you share with?<input className={styles.input} value={audience} maxLength={60} onChange={e=>setAudience(e.target.value)} placeholder="Family, a friend, my class…"/></label><Chooser label="How will you share?" options={formats} value={format} set={setFormat}/><Chooser label="Preparation time" options={times} value={time} set={setTime}/><button className="button button--primary button--lg" disabled={status==='loading'||!audience.trim()} onClick={generate}>{status==='loading'?'Setting the stage…':'Create three sharing plans'}</button>{error&&<p className={styles.error}>{error}</p>}</Panel>
 {ideas.length>0&&<Panel n="2" title="Choose your sharing plan"><div className={styles.ideaGrid}>{ideas.map((x,i)=><button key={x.title} className={`${styles.idea} ${idea?.title===x.title?styles.selected:''}`} onClick={()=>choose(x)} aria-pressed={idea?.title===x.title}><b>◉ 0{i+1}</b><small>{x.format}</small><strong>{x.title}</strong><span>{x.hook}</span></button>)}</div></Panel>}
 {idea&&<><StoryStage filled={filled} total={total} saved={saved}/><Panel n="3" title="Write it in your own words"><p className={styles.coachNote}>ChloeLabs suggests the structure. You write the actual explanation.</p><StageField label="Opening hook" hint={idea.hook} value={hook} set={setHook}/>{idea.keyPoints.map((point,i)=><StageField key={point} label={`Key point ${i+1}`} hint={point} value={points[i]} set={v=>setPoints(current=>current.map((x,n)=>n===i?v:x))}/>) }<StageField label="Audience activity" hint={idea.audienceActivity} value={activity} set={setActivity}/><StageField label="Closing" hint={idea.closing} value={closing} set={setClosing}/></Panel>
 <Panel n="4" title="Rehearse and check understanding"><div className={styles.rehearsal}><span>🎙️</span><div><strong>Say it aloud</strong><p>Could {audience} follow the idea without seeing your notes?</p><p><b>Ask them:</b> {idea.checkQuestion}</p></div></div><button className={`${styles.rehearseButton} ${rehearsed?styles.rehearsed:''}`} onClick={()=>setRehearsed(!rehearsed)} aria-pressed={rehearsed}>{rehearsed?'✓ I rehearsed it':'Mark rehearsal complete'}</button><button className="button button--primary button--lg" disabled={!rehearsed||filled<total} onClick={save}>Save to my Sharing Notebook</button>{saved&&<><p className={styles.saved}>Bravo! Your sharing plan is saved privately in this browser.</p><Link className="button button--secondary button--lg" to="/my-lab-notebook">View My Lab Notebook</Link></>}</Panel></>}</div></main></Layout>}
function StoryStage({filled,total,saved}){return <section className={styles.stage} aria-label="Interactive story stage"><div className={styles.curtainLeft}/><div className={styles.curtainRight}/><div className={styles.spotlight}/><div className={styles.stageSign}>{saved?'BRAVO!':'YOUR STORY'}</div><div className={styles.stageLights}>{Array.from({length:total},(_,i)=><i className={i<filled?styles.lightOn:''} key={i}/>)}</div><span className={styles.microphone}>🎙️</span></section>}
function StageField({label,hint,value,set}){return <label className={styles.stageField}><strong>{label}</strong><small>Coach’s cue: {hint}</small><textarea value={value} onChange={e=>set(e.target.value)} rows={3} placeholder="My own words…"/></label>}
function Panel({n,title,children}){return <section className={styles.panel}><span className={styles.number}>{n}</span><div><Heading as="h2">{title}</Heading>{children}</div></section>}
function Chooser({label,options,value,set}){return <fieldset className={styles.fieldset}><legend>{label}</legend><div className={styles.chips}>{options.map(x=><button type="button" className={value===x?styles.chipOn:''} aria-pressed={value===x} onClick={()=>set(x)} key={x}>{x}</button>)}</div></fieldset>}
